### ISSUE TITLE
Cannot create order with this library: L2 signature error

### ISSUE THREAD

**Issue by edgeofthegame2** [ApeX-Protocol/apexpro-connector-java#3]
Just downloaded this library with examples. Getting position and order data works fine. Canceling of orders works fine. But creating orders gives this error:

Response =====> {"code":3,"msg":"L2 signature error, please check your wallet and re-sign.","key":"INVALID_L2_SIGNATURE","detail":

------------------------------

Exception in thread "main" exchange.apexpro.connector.exception.ApexProApiException: [Executing] 3: L2 signature error, please check your wallet and re-sign.
        at exchange.apexpro.connector.impl.RestApiInvoker.checkResponse(RestApiInvoker.java:38)
        at exchange.apexpro.connector.impl.RestApiInvoker.callSync(RestApiInvoker.java:65)
        at exchange.apexpro.connector.impl.SyncRequestImpl.createOrder(SyncRequestImpl.java:78)
        at exchange.apexpro.connector.examples.trade.CreateOrder.main(CreateOrder.java:40)

**Comment by edgeofthegame2** [comment]
switched to python, it works fine.
